/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandSpreadVel.srv */
#ifndef WAM_SRVS_SERVICE_BHANDSPREADVEL_H
#define WAM_SRVS_SERVICE_BHANDSPREADVEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandSpreadVelRequest_ {
  typedef BHandSpreadVelRequest_<ContainerAllocator> Type;

  BHandSpreadVelRequest_()
  : velocity(0.0)
  {
  }

  BHandSpreadVelRequest_(const ContainerAllocator& _alloc)
  : velocity(0.0)
  {
  }

  typedef float _velocity_type;
  float velocity;


  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandSpreadVelRequest
typedef  ::wam_srvs::BHandSpreadVelRequest_<std::allocator<void> > BHandSpreadVelRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelRequest> BHandSpreadVelRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelRequest const> BHandSpreadVelRequestConstPtr;


template <class ContainerAllocator>
struct BHandSpreadVelResponse_ {
  typedef BHandSpreadVelResponse_<ContainerAllocator> Type;

  BHandSpreadVelResponse_()
  {
  }

  BHandSpreadVelResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandSpreadVelResponse
typedef  ::wam_srvs::BHandSpreadVelResponse_<std::allocator<void> > BHandSpreadVelResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelResponse> BHandSpreadVelResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandSpreadVelResponse const> BHandSpreadVelResponseConstPtr;

struct BHandSpreadVel
{

typedef BHandSpreadVelRequest Request;
typedef BHandSpreadVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandSpreadVel
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4ff88b32504f688ULL;
  static const uint64_t static_value2 = 0x719a85e0753f63ceULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadVelRequest";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 velocity\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadVelResponse";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandSpreadVelRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandSpreadVelResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandSpreadVel> {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandSpreadVel&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandSpreadVel> {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadVel";
  }

  static const char* value(const wam_srvs::BHandSpreadVel&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadVel";
  }

  static const char* value(const wam_srvs::BHandSpreadVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadVel";
  }

  static const char* value(const wam_srvs::BHandSpreadVelResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDSPREADVEL_H

