/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandGraspVel.srv */
#ifndef WAM_SRVS_SERVICE_BHANDGRASPVEL_H
#define WAM_SRVS_SERVICE_BHANDGRASPVEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandGraspVelRequest_ {
  typedef BHandGraspVelRequest_<ContainerAllocator> Type;

  BHandGraspVelRequest_()
  : velocity(0.0)
  {
  }

  BHandGraspVelRequest_(const ContainerAllocator& _alloc)
  : velocity(0.0)
  {
  }

  typedef float _velocity_type;
  float velocity;


  typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandGraspVelRequest
typedef  ::wam_srvs::BHandGraspVelRequest_<std::allocator<void> > BHandGraspVelRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelRequest> BHandGraspVelRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelRequest const> BHandGraspVelRequestConstPtr;


template <class ContainerAllocator>
struct BHandGraspVelResponse_ {
  typedef BHandGraspVelResponse_<ContainerAllocator> Type;

  BHandGraspVelResponse_()
  {
  }

  BHandGraspVelResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandGraspVelResponse
typedef  ::wam_srvs::BHandGraspVelResponse_<std::allocator<void> > BHandGraspVelResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelResponse> BHandGraspVelResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandGraspVelResponse const> BHandGraspVelResponseConstPtr;

struct BHandGraspVel
{

typedef BHandGraspVelRequest Request;
typedef BHandGraspVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandGraspVel
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe4ff88b32504f688ULL;
  static const uint64_t static_value2 = 0x719a85e0753f63ceULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspVelRequest";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 velocity\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspVelResponse";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandGraspVelRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandGraspVelRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandGraspVelResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandGraspVelResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandGraspVel> {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandGraspVel&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandGraspVel> {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspVel";
  }

  static const char* value(const wam_srvs::BHandGraspVel&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandGraspVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandGraspVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspVel";
  }

  static const char* value(const wam_srvs::BHandGraspVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const wam_srvs::BHandGraspVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandGraspVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspVel";
  }

  static const char* value(const wam_srvs::BHandGraspVelResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDGRASPVEL_H

