/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandFingerVel.srv */
#ifndef WAM_SRVS_SERVICE_BHANDFINGERVEL_H
#define WAM_SRVS_SERVICE_BHANDFINGERVEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandFingerVelRequest_ {
  typedef BHandFingerVelRequest_<ContainerAllocator> Type;

  BHandFingerVelRequest_()
  : velocity()
  {
    velocity.assign(0.0);
  }

  BHandFingerVelRequest_(const ContainerAllocator& _alloc)
  : velocity()
  {
    velocity.assign(0.0);
  }

  typedef boost::array<float, 3>  _velocity_type;
  boost::array<float, 3>  velocity;


  typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandFingerVelRequest
typedef  ::wam_srvs::BHandFingerVelRequest_<std::allocator<void> > BHandFingerVelRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelRequest> BHandFingerVelRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelRequest const> BHandFingerVelRequestConstPtr;


template <class ContainerAllocator>
struct BHandFingerVelResponse_ {
  typedef BHandFingerVelResponse_<ContainerAllocator> Type;

  BHandFingerVelResponse_()
  {
  }

  BHandFingerVelResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandFingerVelResponse
typedef  ::wam_srvs::BHandFingerVelResponse_<std::allocator<void> > BHandFingerVelResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelResponse> BHandFingerVelResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandFingerVelResponse const> BHandFingerVelResponseConstPtr;

struct BHandFingerVel
{

typedef BHandFingerVelRequest Request;
typedef BHandFingerVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandFingerVel
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd4b1534f81253843ULL;
  static const uint64_t static_value2 = 0xd8e7435f97fbf189ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerVelRequest";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[3] velocity\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerVelResponse";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandFingerVelRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandFingerVelRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandFingerVelResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandFingerVelResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandFingerVel> {
  static const char* value() 
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const wam_srvs::BHandFingerVel&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandFingerVel> {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerVel";
  }

  static const char* value(const wam_srvs::BHandFingerVel&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const wam_srvs::BHandFingerVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandFingerVelRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerVel";
  }

  static const char* value(const wam_srvs::BHandFingerVelRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const wam_srvs::BHandFingerVelResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandFingerVelResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerVel";
  }

  static const char* value(const wam_srvs::BHandFingerVelResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDFINGERVEL_H

