/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandGraspPos.srv */
#ifndef WAM_SRVS_SERVICE_BHANDGRASPPOS_H
#define WAM_SRVS_SERVICE_BHANDGRASPPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandGraspPosRequest_ {
  typedef BHandGraspPosRequest_<ContainerAllocator> Type;

  BHandGraspPosRequest_()
  : radians(0.0)
  {
  }

  BHandGraspPosRequest_(const ContainerAllocator& _alloc)
  : radians(0.0)
  {
  }

  typedef float _radians_type;
  float radians;


  typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandGraspPosRequest
typedef  ::wam_srvs::BHandGraspPosRequest_<std::allocator<void> > BHandGraspPosRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosRequest> BHandGraspPosRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosRequest const> BHandGraspPosRequestConstPtr;


template <class ContainerAllocator>
struct BHandGraspPosResponse_ {
  typedef BHandGraspPosResponse_<ContainerAllocator> Type;

  BHandGraspPosResponse_()
  {
  }

  BHandGraspPosResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandGraspPosResponse
typedef  ::wam_srvs::BHandGraspPosResponse_<std::allocator<void> > BHandGraspPosResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosResponse> BHandGraspPosResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandGraspPosResponse const> BHandGraspPosResponseConstPtr;

struct BHandGraspPos
{

typedef BHandGraspPosRequest Request;
typedef BHandGraspPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandGraspPos
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x718158cfca4f89c6ULL;
  static const uint64_t static_value2 = 0x952f799c53697f42ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspPosRequest";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 radians\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspPosResponse";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandGraspPosRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.radians);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandGraspPosRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandGraspPosResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandGraspPosResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandGraspPos> {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandGraspPos&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandGraspPos> {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspPos";
  }

  static const char* value(const wam_srvs::BHandGraspPos&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandGraspPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandGraspPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspPos";
  }

  static const char* value(const wam_srvs::BHandGraspPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandGraspPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandGraspPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandGraspPos";
  }

  static const char* value(const wam_srvs::BHandGraspPosResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDGRASPPOS_H

