/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandSpreadPos.srv */
#ifndef WAM_SRVS_SERVICE_BHANDSPREADPOS_H
#define WAM_SRVS_SERVICE_BHANDSPREADPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandSpreadPosRequest_ {
  typedef BHandSpreadPosRequest_<ContainerAllocator> Type;

  BHandSpreadPosRequest_()
  : radians(0.0)
  {
  }

  BHandSpreadPosRequest_(const ContainerAllocator& _alloc)
  : radians(0.0)
  {
  }

  typedef float _radians_type;
  float radians;


  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandSpreadPosRequest
typedef  ::wam_srvs::BHandSpreadPosRequest_<std::allocator<void> > BHandSpreadPosRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosRequest> BHandSpreadPosRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosRequest const> BHandSpreadPosRequestConstPtr;


template <class ContainerAllocator>
struct BHandSpreadPosResponse_ {
  typedef BHandSpreadPosResponse_<ContainerAllocator> Type;

  BHandSpreadPosResponse_()
  {
  }

  BHandSpreadPosResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandSpreadPosResponse
typedef  ::wam_srvs::BHandSpreadPosResponse_<std::allocator<void> > BHandSpreadPosResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosResponse> BHandSpreadPosResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandSpreadPosResponse const> BHandSpreadPosResponseConstPtr;

struct BHandSpreadPos
{

typedef BHandSpreadPosRequest Request;
typedef BHandSpreadPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandSpreadPos
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x718158cfca4f89c6ULL;
  static const uint64_t static_value2 = 0x952f799c53697f42ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadPosRequest";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 radians\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadPosResponse";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.radians);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandSpreadPosRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandSpreadPosResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandSpreadPos> {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandSpreadPos&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandSpreadPos> {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadPos";
  }

  static const char* value(const wam_srvs::BHandSpreadPos&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadPos";
  }

  static const char* value(const wam_srvs::BHandSpreadPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandSpreadPos";
  }

  static const char* value(const wam_srvs::BHandSpreadPosResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDSPREADPOS_H

