/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/BHandFingerPos.srv */
#ifndef WAM_SRVS_SERVICE_BHANDFINGERPOS_H
#define WAM_SRVS_SERVICE_BHANDFINGERPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct BHandFingerPosRequest_ {
  typedef BHandFingerPosRequest_<ContainerAllocator> Type;

  BHandFingerPosRequest_()
  : radians()
  {
    radians.assign(0.0);
  }

  BHandFingerPosRequest_(const ContainerAllocator& _alloc)
  : radians()
  {
    radians.assign(0.0);
  }

  typedef boost::array<float, 3>  _radians_type;
  boost::array<float, 3>  radians;


  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandFingerPosRequest
typedef  ::wam_srvs::BHandFingerPosRequest_<std::allocator<void> > BHandFingerPosRequest;

typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest> BHandFingerPosRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosRequest const> BHandFingerPosRequestConstPtr;


template <class ContainerAllocator>
struct BHandFingerPosResponse_ {
  typedef BHandFingerPosResponse_<ContainerAllocator> Type;

  BHandFingerPosResponse_()
  {
  }

  BHandFingerPosResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BHandFingerPosResponse
typedef  ::wam_srvs::BHandFingerPosResponse_<std::allocator<void> > BHandFingerPosResponse;

typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosResponse> BHandFingerPosResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::BHandFingerPosResponse const> BHandFingerPosResponseConstPtr;

struct BHandFingerPos
{

typedef BHandFingerPosRequest Request;
typedef BHandFingerPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BHandFingerPos
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb8c122f38450d030ULL;
  static const uint64_t static_value2 = 0x2ba1a30c9c588995ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerPosRequest";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[3] radians\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerPosResponse";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandFingerPosRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.radians);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandFingerPosRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::BHandFingerPosResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BHandFingerPosResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::BHandFingerPos> {
  static const char* value() 
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const wam_srvs::BHandFingerPos&) { return value(); } 
};

template<>
struct DataType<wam_srvs::BHandFingerPos> {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerPos";
  }

  static const char* value(const wam_srvs::BHandFingerPos&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const wam_srvs::BHandFingerPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandFingerPosRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerPos";
  }

  static const char* value(const wam_srvs::BHandFingerPosRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const wam_srvs::BHandFingerPosResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::BHandFingerPosResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/BHandFingerPos";
  }

  static const char* value(const wam_srvs::BHandFingerPosResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_BHANDFINGERPOS_H

