/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/GravityComp.srv */
#ifndef WAM_SRVS_SERVICE_GRAVITYCOMP_H
#define WAM_SRVS_SERVICE_GRAVITYCOMP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct GravityCompRequest_ {
  typedef GravityCompRequest_<ContainerAllocator> Type;

  GravityCompRequest_()
  : gravity(false)
  {
  }

  GravityCompRequest_(const ContainerAllocator& _alloc)
  : gravity(false)
  {
  }

  typedef uint8_t _gravity_type;
  uint8_t gravity;


  typedef boost::shared_ptr< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::GravityCompRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GravityCompRequest
typedef  ::wam_srvs::GravityCompRequest_<std::allocator<void> > GravityCompRequest;

typedef boost::shared_ptr< ::wam_srvs::GravityCompRequest> GravityCompRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::GravityCompRequest const> GravityCompRequestConstPtr;


template <class ContainerAllocator>
struct GravityCompResponse_ {
  typedef GravityCompResponse_<ContainerAllocator> Type;

  GravityCompResponse_()
  {
  }

  GravityCompResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::GravityCompResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GravityCompResponse
typedef  ::wam_srvs::GravityCompResponse_<std::allocator<void> > GravityCompResponse;

typedef boost::shared_ptr< ::wam_srvs::GravityCompResponse> GravityCompResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::GravityCompResponse const> GravityCompResponseConstPtr;

struct GravityComp
{

typedef GravityCompRequest Request;
typedef GravityCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GravityComp
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::GravityCompRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const  ::wam_srvs::GravityCompRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf83a9fe078fab986ULL;
  static const uint64_t static_value2 = 0x5d863fbf215e1c14ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/GravityCompRequest";
  }

  static const char* value(const  ::wam_srvs::GravityCompRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool gravity\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::GravityCompRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::GravityCompRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::GravityCompResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::GravityCompResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/GravityCompResponse";
  }

  static const char* value(const  ::wam_srvs::GravityCompResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::GravityCompResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::GravityCompResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::GravityCompRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.gravity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GravityCompRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::GravityCompResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GravityCompResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::GravityComp> {
  static const char* value() 
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const wam_srvs::GravityComp&) { return value(); } 
};

template<>
struct DataType<wam_srvs::GravityComp> {
  static const char* value() 
  {
    return "wam_srvs/GravityComp";
  }

  static const char* value(const wam_srvs::GravityComp&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::GravityCompRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const wam_srvs::GravityCompRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::GravityCompRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/GravityComp";
  }

  static const char* value(const wam_srvs::GravityCompRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::GravityCompResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const wam_srvs::GravityCompResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::GravityCompResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/GravityComp";
  }

  static const char* value(const wam_srvs::GravityCompResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_GRAVITYCOMP_H

