/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/Hold.srv */
#ifndef WAM_SRVS_SERVICE_HOLD_H
#define WAM_SRVS_SERVICE_HOLD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct HoldRequest_ {
  typedef HoldRequest_<ContainerAllocator> Type;

  HoldRequest_()
  : hold(false)
  {
  }

  HoldRequest_(const ContainerAllocator& _alloc)
  : hold(false)
  {
  }

  typedef uint8_t _hold_type;
  uint8_t hold;


  typedef boost::shared_ptr< ::wam_srvs::HoldRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::HoldRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HoldRequest
typedef  ::wam_srvs::HoldRequest_<std::allocator<void> > HoldRequest;

typedef boost::shared_ptr< ::wam_srvs::HoldRequest> HoldRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::HoldRequest const> HoldRequestConstPtr;


template <class ContainerAllocator>
struct HoldResponse_ {
  typedef HoldResponse_<ContainerAllocator> Type;

  HoldResponse_()
  {
  }

  HoldResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::HoldResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::HoldResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HoldResponse
typedef  ::wam_srvs::HoldResponse_<std::allocator<void> > HoldResponse;

typedef boost::shared_ptr< ::wam_srvs::HoldResponse> HoldResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::HoldResponse const> HoldResponseConstPtr;

struct Hold
{

typedef HoldRequest Request;
typedef HoldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Hold
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::HoldRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::HoldRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::HoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "797a139a4299aebd587b00a7001c67f7";
  }

  static const char* value(const  ::wam_srvs::HoldRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x797a139a4299aebdULL;
  static const uint64_t static_value2 = 0x587b00a7001c67f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::HoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/HoldRequest";
  }

  static const char* value(const  ::wam_srvs::HoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::HoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool hold\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::HoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::HoldRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::HoldResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::HoldResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::HoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::HoldResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::HoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/HoldResponse";
  }

  static const char* value(const  ::wam_srvs::HoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::HoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::HoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::HoldResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::HoldRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.hold);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HoldRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::HoldResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HoldResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::Hold> {
  static const char* value() 
  {
    return "797a139a4299aebd587b00a7001c67f7";
  }

  static const char* value(const wam_srvs::Hold&) { return value(); } 
};

template<>
struct DataType<wam_srvs::Hold> {
  static const char* value() 
  {
    return "wam_srvs/Hold";
  }

  static const char* value(const wam_srvs::Hold&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::HoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "797a139a4299aebd587b00a7001c67f7";
  }

  static const char* value(const wam_srvs::HoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::HoldRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/Hold";
  }

  static const char* value(const wam_srvs::HoldRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::HoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "797a139a4299aebd587b00a7001c67f7";
  }

  static const char* value(const wam_srvs::HoldResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::HoldResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/Hold";
  }

  static const char* value(const wam_srvs::HoldResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_HOLD_H

