/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/JointMove.srv */
#ifndef WAM_SRVS_SERVICE_JOINTMOVE_H
#define WAM_SRVS_SERVICE_JOINTMOVE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct JointMoveRequest_ {
  typedef JointMoveRequest_<ContainerAllocator> Type;

  JointMoveRequest_()
  : joints()
  {
  }

  JointMoveRequest_(const ContainerAllocator& _alloc)
  : joints(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joints_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  joints;


  typedef boost::shared_ptr< ::wam_srvs::JointMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::JointMoveRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointMoveRequest
typedef  ::wam_srvs::JointMoveRequest_<std::allocator<void> > JointMoveRequest;

typedef boost::shared_ptr< ::wam_srvs::JointMoveRequest> JointMoveRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::JointMoveRequest const> JointMoveRequestConstPtr;


template <class ContainerAllocator>
struct JointMoveResponse_ {
  typedef JointMoveResponse_<ContainerAllocator> Type;

  JointMoveResponse_()
  {
  }

  JointMoveResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::JointMoveResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct JointMoveResponse
typedef  ::wam_srvs::JointMoveResponse_<std::allocator<void> > JointMoveResponse;

typedef boost::shared_ptr< ::wam_srvs::JointMoveResponse> JointMoveResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::JointMoveResponse const> JointMoveResponseConstPtr;

struct JointMove
{

typedef JointMoveRequest Request;
typedef JointMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct JointMove
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::JointMoveRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::JointMoveRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::JointMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const  ::wam_srvs::JointMoveRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe2a0e438b445b98dULL;
  static const uint64_t static_value2 = 0xef0f0ba6a2a85f58ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::JointMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/JointMoveRequest";
  }

  static const char* value(const  ::wam_srvs::JointMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::JointMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] joints\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::JointMoveRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::JointMoveResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::JointMoveResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/JointMoveResponse";
  }

  static const char* value(const  ::wam_srvs::JointMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::JointMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::JointMoveResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::JointMoveRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.joints);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointMoveRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::JointMoveResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct JointMoveResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::JointMove> {
  static const char* value() 
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const wam_srvs::JointMove&) { return value(); } 
};

template<>
struct DataType<wam_srvs::JointMove> {
  static const char* value() 
  {
    return "wam_srvs/JointMove";
  }

  static const char* value(const wam_srvs::JointMove&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::JointMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const wam_srvs::JointMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::JointMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/JointMove";
  }

  static const char* value(const wam_srvs::JointMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::JointMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e2a0e438b445b98def0f0ba6a2a85f58";
  }

  static const char* value(const wam_srvs::JointMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::JointMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/JointMove";
  }

  static const char* value(const wam_srvs::JointMoveResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_JOINTMOVE_H

