/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_srvs/srv/OrtnMove.srv */
#ifndef WAM_SRVS_SERVICE_ORTNMOVE_H
#define WAM_SRVS_SERVICE_ORTNMOVE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace wam_srvs
{
template <class ContainerAllocator>
struct OrtnMoveRequest_ {
  typedef OrtnMoveRequest_<ContainerAllocator> Type;

  OrtnMoveRequest_()
  : orientation()
  {
    orientation.assign(0.0);
  }

  OrtnMoveRequest_(const ContainerAllocator& _alloc)
  : orientation()
  {
    orientation.assign(0.0);
  }

  typedef boost::array<float, 4>  _orientation_type;
  boost::array<float, 4>  orientation;


  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct OrtnMoveRequest
typedef  ::wam_srvs::OrtnMoveRequest_<std::allocator<void> > OrtnMoveRequest;

typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest> OrtnMoveRequestPtr;
typedef boost::shared_ptr< ::wam_srvs::OrtnMoveRequest const> OrtnMoveRequestConstPtr;


template <class ContainerAllocator>
struct OrtnMoveResponse_ {
  typedef OrtnMoveResponse_<ContainerAllocator> Type;

  OrtnMoveResponse_()
  {
  }

  OrtnMoveResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct OrtnMoveResponse
typedef  ::wam_srvs::OrtnMoveResponse_<std::allocator<void> > OrtnMoveResponse;

typedef boost::shared_ptr< ::wam_srvs::OrtnMoveResponse> OrtnMoveResponsePtr;
typedef boost::shared_ptr< ::wam_srvs::OrtnMoveResponse const> OrtnMoveResponseConstPtr;

struct OrtnMove
{

typedef OrtnMoveRequest Request;
typedef OrtnMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct OrtnMove
} // namespace wam_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x86f723fe9a4be897ULL;
  static const uint64_t static_value2 = 0x9be87cd065276584ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/OrtnMoveRequest";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[4] orientation\n\
\n\
";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/OrtnMoveResponse";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::OrtnMoveRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.orientation);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OrtnMoveRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_srvs::OrtnMoveResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OrtnMoveResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<wam_srvs::OrtnMove> {
  static const char* value() 
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const wam_srvs::OrtnMove&) { return value(); } 
};

template<>
struct DataType<wam_srvs::OrtnMove> {
  static const char* value() 
  {
    return "wam_srvs/OrtnMove";
  }

  static const char* value(const wam_srvs::OrtnMove&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::OrtnMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const wam_srvs::OrtnMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::OrtnMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/OrtnMove";
  }

  static const char* value(const wam_srvs::OrtnMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<wam_srvs::OrtnMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const wam_srvs::OrtnMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<wam_srvs::OrtnMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_srvs/OrtnMove";
  }

  static const char* value(const wam_srvs::OrtnMoveResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAM_SRVS_SERVICE_ORTNMOVE_H

