"""autogenerated by genpy from wam_node/HandPos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HandPos(genpy.Message):
  _md5sum = "82d22a9cd69bfae0453346c187d5c4d2"
  _type = "wam_node/HandPos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 f1
int32 f2
int32 f3
int32 spread

"""
  __slots__ = ['f1','f2','f3','spread']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       f1,f2,f3,spread

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HandPos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.f1 is None:
        self.f1 = 0
      if self.f2 is None:
        self.f2 = 0
      if self.f3 is None:
        self.f3 = 0
      if self.spread is None:
        self.spread = 0
    else:
      self.f1 = 0
      self.f2 = 0
      self.f3 = 0
      self.spread = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.f1, _x.f2, _x.f3, _x.spread))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.f1, _x.f2, _x.f3, _x.spread,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i.pack(_x.f1, _x.f2, _x.f3, _x.spread))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.f1, _x.f2, _x.f3, _x.spread,) = _struct_4i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i = struct.Struct("<4i")
