/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_msgs/msg/RTCartPos.msg */
#ifndef WAM_MSGS_MESSAGE_RTCARTPOS_H
#define WAM_MSGS_MESSAGE_RTCARTPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace wam_msgs
{
template <class ContainerAllocator>
struct RTCartPos_ {
  typedef RTCartPos_<ContainerAllocator> Type;

  RTCartPos_()
  : position()
  , rate_limits()
  {
    position.assign(0.0);
    rate_limits.assign(0.0);
  }

  RTCartPos_(const ContainerAllocator& _alloc)
  : position()
  , rate_limits()
  {
    position.assign(0.0);
    rate_limits.assign(0.0);
  }

  typedef boost::array<float, 3>  _position_type;
  boost::array<float, 3>  position;

  typedef boost::array<float, 3>  _rate_limits_type;
  boost::array<float, 3>  rate_limits;


  typedef boost::shared_ptr< ::wam_msgs::RTCartPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::RTCartPos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RTCartPos
typedef  ::wam_msgs::RTCartPos_<std::allocator<void> > RTCartPos;

typedef boost::shared_ptr< ::wam_msgs::RTCartPos> RTCartPosPtr;
typedef boost::shared_ptr< ::wam_msgs::RTCartPos const> RTCartPosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::wam_msgs::RTCartPos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::wam_msgs::RTCartPos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_msgs::RTCartPos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_msgs::RTCartPos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::RTCartPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f40423d4ca09896785d982c621cba554";
  }

  static const char* value(const  ::wam_msgs::RTCartPos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf40423d4ca098967ULL;
  static const uint64_t static_value2 = 0x85d982c621cba554ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::RTCartPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_msgs/RTCartPos";
  }

  static const char* value(const  ::wam_msgs::RTCartPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::RTCartPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[3] position\n\
float32[3] rate_limits\n\
\n\
";
  }

  static const char* value(const  ::wam_msgs::RTCartPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_msgs::RTCartPos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_msgs::RTCartPos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.position);
    stream.next(m.rate_limits);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RTCartPos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::RTCartPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::wam_msgs::RTCartPos_<ContainerAllocator> & v) 
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "rate_limits[]" << std::endl;
    for (size_t i = 0; i < v.rate_limits.size(); ++i)
    {
      s << indent << "  rate_limits[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rate_limits[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_RTCARTPOS_H

