/* Auto-generated by genmsg_cpp for file /home/robot/fuerte_workspace/sandbox/barrett-ros-pkg/wam_common/wam_msgs/msg/RTOrtnPos.msg */
#ifndef WAM_MSGS_MESSAGE_RTORTNPOS_H
#define WAM_MSGS_MESSAGE_RTORTNPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace wam_msgs
{
template <class ContainerAllocator>
struct RTOrtnPos_ {
  typedef RTOrtnPos_<ContainerAllocator> Type;

  RTOrtnPos_()
  : orientation()
  , rate_limits()
  {
    orientation.assign(0.0);
    rate_limits.assign(0.0);
  }

  RTOrtnPos_(const ContainerAllocator& _alloc)
  : orientation()
  , rate_limits()
  {
    orientation.assign(0.0);
    rate_limits.assign(0.0);
  }

  typedef boost::array<float, 4>  _orientation_type;
  boost::array<float, 4>  orientation;

  typedef boost::array<float, 4>  _rate_limits_type;
  boost::array<float, 4>  rate_limits;


  typedef boost::shared_ptr< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_msgs::RTOrtnPos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RTOrtnPos
typedef  ::wam_msgs::RTOrtnPos_<std::allocator<void> > RTOrtnPos;

typedef boost::shared_ptr< ::wam_msgs::RTOrtnPos> RTOrtnPosPtr;
typedef boost::shared_ptr< ::wam_msgs::RTOrtnPos const> RTOrtnPosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::wam_msgs::RTOrtnPos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::wam_msgs::RTOrtnPos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace wam_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wam_msgs::RTOrtnPos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5b352081db430205c87e0e439f09a0b2";
  }

  static const char* value(const  ::wam_msgs::RTOrtnPos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5b352081db430205ULL;
  static const uint64_t static_value2 = 0xc87e0e439f09a0b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wam_msgs/RTOrtnPos";
  }

  static const char* value(const  ::wam_msgs::RTOrtnPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[4] orientation\n\
float32[4] rate_limits\n\
\n\
";
  }

  static const char* value(const  ::wam_msgs::RTOrtnPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::wam_msgs::RTOrtnPos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wam_msgs::RTOrtnPos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.orientation);
    stream.next(m.rate_limits);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RTOrtnPos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_msgs::RTOrtnPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::wam_msgs::RTOrtnPos_<ContainerAllocator> & v) 
  {
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "rate_limits[]" << std::endl;
    for (size_t i = 0; i < v.rate_limits.size(); ++i)
    {
      s << indent << "  rate_limits[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rate_limits[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // WAM_MSGS_MESSAGE_RTORTNPOS_H

